### ISSUE TITLE
Can't use boolean literal `no` as a part of a poetic number literal

### ISSUE THREAD

**Issue by hannotify** [holly-cummins/bon-jova-rockstar-implementation#79]
Rockstar program:

```
The tide is low. A ball flung-about, beach abandoned, no soiree beats the shore
Whisper the tide
```

Output on Satriani:

```
3.1415926535
```

Output on Bon Jova:

```
2024-01-31 10:38:12,027 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /rockstar/concept-demo-2-poetic-number-literals.rock failed, error id: 5c122d65-0bf8-4542-8ec0-621941358e87-1: java.lang.VerifyError: Control flow falls through code end
Exception Details:
  Location:
    concept-demo-2-poetic-number-literals.main([Ljava/lang/String;)V @6: <invalid>
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 1400 19b3 001c                         

        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:534)
        at java.base/java.lang.Class.forName(Class.java:513)
        at org.example.bon.jova.quarkus.extension.runtime.RockstarResource.runClassCapturingSystemOut(RockstarResource.java:40)
        at org.example.bon.jova.quarkus.extension.runtime.RockstarResource.runRockstarProgram(RockstarResource.java:25)
        (rest of stacktrace omitted for brevity)

line 1:54 mismatched input 'no' expecting {<EOF>, NL}
line 1:64 no viable alternative at input 'soiree beats'
```

**Comment by holly-cummins** [comment]
Fixed by #86
